# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=main (ubuntu-18.04, 3.8.8)
      - check-success=main (ubuntu-18.04, 3.9.4)
      - check-success=main (macos-10.15, 3.8.8)
      - check-success=main (macos-10.15, 3.9.4)
    actions:
      merge:
        method: squash
        merge_bot_account: dotanukibot

  - name: Be author's friend
    conditions:
      - author~=ubiratansoares
      - check-success=main (ubuntu-18.04, 3.8.8)
      - check-success=main (ubuntu-18.04, 3.9.4)
      - check-success=main (macos-10.15, 3.8.8)
      - check-success=main (macos-10.15, 3.9.4)
    actions:
      merge:
        method: squash
        merge_bot_account: dotanukibot
