# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=main (ubuntu-latest, 3.8.7)
      - check-success=main (ubuntu-latest, 3.9.1)
      - check-success=main (macos-latest, 3.8.7)
      - check-success=main (macos-latest, 3.9.1)
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=ubiratansoares
      - check-success=main (ubuntu-latest, 3.8.7)
      - check-success=main (ubuntu-latest, 3.9.1)
      - check-success=main (macos-latest, 3.8.7)
      - check-success=main (macos-latest, 3.9.1)
    actions:
      merge:
        method: squash
