name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-18.04', 'macos-10.15']
        python: ['3.8.8', '3.9.2']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Project checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: make setup

      - name: Check codestyle
        run: make inspect

      - name: Run tests
        run: make test

      - name: Build Package
        run: make build

      - name: Upload test reports to Codecov
        uses: codecov/codecov-action@v1.3.1
