name: Publish

on:
  release:
    types:
      - created

jobs:
  publish_on_pypi:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Project checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: make setup

      - name: Publish to Pypi
        run: make deploy token=${{ secrets.PYPI_TOKEN }}

  publish_on_ghcr:
    runs-on: ubuntu-18.04
    needs: [publish_on_pypi]
    timeout-minutes: 10
    permissions:
      packages: write
      contents: read

    steps:
      - name: Project checkout
        uses: actions/checkout@v2.3.4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container Image
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
